version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: backend
    restart: always
    depends_on:
      - mongodb
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
